language: ruby
rvm:
  - 1.9.3

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - RAILS_ENV=test bundle exec rspec spec

before_script:
  - psql -c 'create database devops_test' -U postgres
